### ISSUE TITLE
Color

### ISSUE THREAD

**Issue by Brenaki** [Luciano0415/Praticas#1]
E aí Luciano, queria falar que tá daora o seu codigo, mas as cores que você escolheu que não ficou muito bom.
Se quiser mudar para deixar mais light e combinando.

## Usa umas cores assim:

![image](https://user-images.githubusercontent.com/91611155/139162304-55ceb036-efb2-4ecd-ab2f-8678921bb161.png)

## Alteração

![image](https://user-images.githubusercontent.com/91611155/139162397-5fbad6ef-8f41-4f77-b5d6-afeda38e745a.png)

![image](https://user-images.githubusercontent.com/91611155/139162433-ac58c7e9-a5de-4243-b040-2f39dbda9c68.png)

**Comment by Luciano0415** [comment]
@Brenaki muito obrigado, vou fazer isso sim, sou iniciante  nesse mundo de programação, estou aprendendo aos poucos, mais agradeço muito
